const fetch = require("node-fetch");
const FormData = require("form-data");
const { MAIN_KEYS } = require("./geminikey.js");
require("dotenv").config();

const MW_API = process.env.MW_API;
const USERNAME = process.env.BOTUSERNAME;
const PASSWORD = process.env.BOTPASSWORD;

// -------------------- DYNAMIC IMPORT (ESM-ONLY GEMINI) --------------------
let GoogleGenAI;
async function getGeminiClient(apiKey) {
	if (!GoogleGenAI) {
		const mod = await import("@google/genai");
		GoogleGenAI = mod.GoogleGenAI;
	}
	return new GoogleGenAI({ apiKey });
}

// -------------------- GEMINI REQUEST HANDLER (MULTI-KEY SUPPORT) --------------------
async function runWithMainKeys(fn) {
	const keys = Array.isArray(MAIN_KEYS) ? MAIN_KEYS : [MAIN_KEYS];
	if (!keys.length) throw new Error("No Gemini main keys set!");

	let lastErr;
	for (const key of keys) {
		try {
			const gemini = await getGeminiClient(key);
			return await fn(gemini);
		} catch (err) {
			const msg = err?.message || err?.toString();
			console.error(`Gemini request failed with key ${key.slice(0, 15)}...:`, msg);

			// skip over quota or transient errors
			if (msg.includes("RESOURCE_EXHAUSTED") || msg.includes("429") || msg.includes("503")) {
				lastErr = err;
				continue;
			}
			throw err;
		}
	}
	throw lastErr || new Error("All Gemini main keys failed!");
}

// -------------------- MEDIAWIKI LOGIN --------------------
async function login() {
	// Step 1: Get login token
	let res = await fetch(`${MW_API}?action=query&meta=tokens&type=login&format=json`);
	let data = await res.json();
	const loginToken = data.query.tokens.logintoken;

	// Step 2: Log in
	const form = new FormData();
	form.append("action", "login");
	form.append("lgname", USERNAME);
	form.append("lgpassword", PASSWORD);
	form.append("lgtoken", loginToken);
	form.append("format", "json");

	const cookieJar = [];
	res = await fetch(MW_API, { method: "POST", body: form, redirect: "manual" });
	const setCookie = res.headers.raw()["set-cookie"];
	if (setCookie) cookieJar.push(...setCookie.map((c) => c.split(";")[0]));
	const cookies = cookieJar.join("; ");

	console.log("✅ Logged in as", USERNAME);

	// Step 3: Get CSRF token
	res = await fetch(`${MW_API}?action=query&meta=tokens&format=json`, {
		headers: { Cookie: cookies },
	});
	data = await res.json();
	const csrfToken = data.query.tokens.csrftoken;

	return { cookies, csrfToken };
}

// -------------------- FETCH FILE LIST --------------------
async function getFileList(cookies) {
	const res = await fetch(`${MW_API}?action=query&list=allimages&ailimit=50&format=json`, {
		headers: { Cookie: cookies },
	});
	const data = await res.json();
	return data.query.allimages.map((f) => f.name);
}

// -------------------- DELETE FILE --------------------
async function deleteFile(fileName, csrfToken, cookies) {
	const form = new FormData();
	form.append("action", "delete");
	form.append("title", "File:" + fileName);
	form.append("reason", "Non-descriptive filename (auto-detected by Gemini)");
	form.append("token", csrfToken);
	form.append("format", "json");

	const res = await fetch(MW_API, {
		method: "POST",
		headers: { Cookie: cookies },
		body: form,
	});

	const data = await res.json();
	if (data.error) {
		console.error("⚠️ Failed to delete", fileName, data.error.info);
	} else {
		console.log("🗑️ Deleted", fileName);
	}
}

// -------------------- GEMINI FILENAME CHECK --------------------
async function isNonDescriptive(name) {
	return await runWithMainKeys(async (gemini) => {
		const prompt = `Is this filename non-descriptive or autogenerated? 
Only reply with "yes" if it's a generic, gibberish, or camera-style name 
like "Screenshot 2025-11-11.png" or "IMG_2345.jpg".
Filename: ${name}`;

		const result = await gemini.models.generateContent({
			model: "gemini-2.5-flash",
			contents: [{ role: "user", parts: [{ text: prompt }] }],
			maxOutputTokens: 50,
		});

		const text = result.response.candidates?.[0]?.content?.parts?.[0]?.text?.toLowerCase() || "";
		return text.includes("yes");
	});
}

// -------------------- MAIN --------------------
(async () => {
	const { cookies, csrfToken } = await login();
	const files = await getFileList(cookies);

	for (const file of files) {
		const bad = await isNonDescriptive(file);
		if (bad) {
			console.log("❌ Non-descriptive:", file);
			await deleteFile(file, csrfToken, cookies);
		} else {
			console.log("✅ Descriptive:", file);
		}
	}
})();
